### ISSUE TITLE
QueryFlag is not encoded correctly

### ISSUE THREAD

**Issue by fizruk** [haskell-servant/servant-js#11]
If you try to use `QueryFlag` you get invalid JavaScript.

The reason is [this line](https://github.com/haskell-servant/servant-js/blob/master/src/Servant/JS/Internal.hs#L186) in `paramToStr` function:

```haskell
paramToStr :: QueryArg f -> Bool -> Text
paramToStr qarg notTheEnd =
  case qarg ^. queryArgType of
    Normal -> name
           <> "=' + encodeURIComponent("
           <> name
           <> if notTheEnd then ") + '" else ")"
    Flag   -> name <> "=" -------------------- BAD CODE HERE
    List   -> name
           <> "[]=' + encodeURIComponent("
           <> name
           <> if notTheEnd then ") + '" else ")"
  where name = qarg ^. queryArgName . argName . _PathSegment
```

It should be

```haskell
    Flag   -> name <> "='" -- close the '
```

or 

```haskell
    Flag   -> name <> "'" -- close the '
```

**Comment by asilvestre** [comment]
Hi, 
I don't think this is fixed, for two regular arguments and a flag in between, as of now it generates javascript like this:
` '&arg=' + encodeURIComponent(arg) + '&flag'&arg2='` + encodeURIComponent(arg2)

**Comment by fierce-katie** [comment]
@asilvestre Opened #19.
